---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: drpc
spec:
  preferredCluster: cluster1
  drPolicyRef:
    name: dr-policy
  placementRef:
    kind: Placement
    name: placement
  pvcSelector:
    matchLabels:
      appname: busybox
