---
resources:
  - ../base
namespace: daemonset-rbd
commonLabels:
  app: daemonset-rbd
patches:
  # Customize path to application.
  - target:
      kind: Subscription
      name: subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-path
        value: workloads/daemonset/k8s-regional-rbd
