---
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: ramendr-pv-roles
  namespace: cluster1
spec:
  workload:
    manifests:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: open-cluster-management:klusterlet-work-sa:agent:pv-edit
      rules:
      - apiGroups:
        - ""
        resources:
        - persistentvolumes
        verbs:
        - create
        - get
        - list
        - patch
        - update
        - watch
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: open-cluster-management:klusterlet-work-sa:agent:pv-edit
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: open-cluster-management:klusterlet-work-sa:agent:pv-edit
      subjects:
      - kind: ServiceAccount
        name: klusterlet-work-sa
        namespace: open-cluster-management-agent
---
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: ramendr-pv-roles
  namespace: hub
spec:
  workload:
    manifests:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: open-cluster-management:klusterlet-work-sa:agent:pv-edit
      rules:
      - apiGroups:
        - ""
        resources:
        - persistentvolumes
        verbs:
        - create
        - get
        - list
        - patch
        - update
        - watch
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: open-cluster-management:klusterlet-work-sa:agent:pv-edit
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: open-cluster-management:klusterlet-work-sa:agent:pv-edit
      subjects:
      - kind: ServiceAccount
        name: klusterlet-work-sa
        namespace: open-cluster-management-agent
