---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc
  labels:
    app: busybox-sample
spec:
  preferredCluster: "cluster1"
  drPolicyRef:
    name: dr-policy
  placementRef:
    kind: Placement
    name: busybox-placement
  pvcSelector:
    matchLabels:
      appname: busybox
