---
resources:
  - ../base-odr
namespace: vm-dv
labels:
  - pairs:
      app: vm-dv
patches:
  - target:
      kind: Subscription
      name: subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-path
        value: workloads/kubevirt/vm-dv/odr-regional
