---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-disk
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: cirros-source
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
  # Customize in your overlay.
  storageClassName: STORAGE_CLASS_NAME
  volumeMode: Block
