---
apiVersion: v1
kind: Service
metadata:
  name: win2k22-service
spec:
  ports:
  - name: rdp
    port: 3389
    nodePort: 32689
    protocol: TCP
  - name: http
    port: 8000
    nodePort: 32680
    protocol: TCP
  selector:
    kubevirt.io/domain: win2k22
  type: NodePort
