---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc
  labels:
    app: busybox-sample
spec:
  preferredCluster: "ocp4perf1"
  drPolicyRef:
    name: odr-policy-ocp4perf1-ocp4perf1-5m
  placementRef:
    kind: PlacementRule
    name: busybox-placement
  pvcSelector:
    matchLabels:
      appname: busybox
