---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: busybox-placement
  labels:
    app: busybox-sample
spec:
  schedulerName: "ramen"
  clusterSelector:
    matchLabels:
      'region': 'west'
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterReplicas: 1
