---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: test
    apps.open-cluster-management.io/github-path: busybox
  labels:
    app: busybox-sample
    ramendr: protected
  name: busybox-sub
spec:
    channel: ramen-samples/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: busybox-placement
