---
resources:
  - source.yaml
  - pvc.yaml
  - vm.yaml
  - service.yaml
labels:
  - pairs:
      appname: vm
secretGenerator:
  - name: fedora
    files:
      - test_rsa.pub
generatorOptions:
  disableNameSuffixHash: true
