---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedora
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: fedora
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  # Customize in your overlay.
  storageClassName: STORAGE_CLASS_NAME
  volumeMode: Block
