---
apiVersion: v1
kind: Service
metadata:
  name: fedora
spec:
  ports:
  - name: http
    port: 8000
    nodePort: 30080
    protocol: TCP
  selector:
    kubevirt.io/domain: fedora
  type: NodePort
