---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: fedora
    spec:
      domain:
        cpu:
          cores:
            2
        devices:
          disks:
            - name: fedora
              disk:
                bus: virtio
            - name: cloud-init
              disk:
                bus: virtio
            - name: config
              disk:
                bus: virtio
              serial: config-disk
          interfaces:
            - name: default
              model: virtio
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: fedora
            propagationMethod:
              noCloud: {}
      volumes:
        - name: fedora
          persistentVolumeClaim:
            claimName: fedora
        - name: cloud-init
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd:
                expire: false
              bootcmd:
                - "sudo mkdir -p /mnt/config"
                - "sudo mount /dev/disk/by-id/virtio-config-disk /mnt/config"
              runcmd:
                - "sudo dnf install -y https://github.com/nirs/visitor/releases/download/v0.8.0/visitor-0.8.0-1.fc39.x86_64.rpm"
                - "sudo systemctl enable visitor --now"
        - name: config
          configMap:
            name: fedora
            optional: true
